spring.application.name=chatapp

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://ERMIN\\SQLEXPRESS01:1433;databaseName=chatapp;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:evoltadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Evolttest!}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Turn off SQL printing in the console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
# Stop JDBC debugging and change system packages to only log critical errors/warnings
logging.level.org.springframework.jdbc.core=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
logging.level.org.springframework.boot=WARN

# Minimize general console clutter
spring.main.banner-mode=off

server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB